name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: src

      - name: Run generator
        run: npm run build
        working-directory: src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: codewithduong05

      - name: Deploy SVG
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist
          publish_branch: output