name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
        working-directory: src

      - run: node index.js
        working-directory: src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: codewithduong05

      - name: Convert SVG → PNG
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          mkdir png
          for f in src/frames/*.svg; do
            convert $f png/$(basename ${f%.svg}.png)
          done

      - name: Create GIF
        run: |
          convert -delay 5 -loop 0 png/*.png pacman.gif

      - name: Move output
        run: |
          rm -rf dist
          mkdir dist
          mv pacman.gif dist/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output